_wandb:
    value:
        cli_version: 0.18.1
        code_path: code/train.py
        m: []
        python_version: 3.8.18
        t:
            "1":
                - 1
                - 11
                - 41
                - 49
                - 55
            "2":
                - 1
                - 11
                - 41
                - 49
                - 55
            "3":
                - 1
                - 13
                - 16
                - 23
                - 55
            "4": 3.8.18
            "5": 0.18.1
            "6": 4.41.1
            "8":
                - 5
            "12": 0.18.1
            "13": linux-x86_64
batch:
    value: 1024
learning_rate:
    value: 0.01
